name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with Docker Compose to VM
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 2422
          username: ivan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ivan/compose

            cat <<EOF > /home/ivan/compose/docker-compose.yml
name: catty-reminders

services:
  app:
    image: ghcr.io/ivanalehin/catty-reminders:latest
    container_name: catty-app
    ports:
      - "8181:8181"
    volumes:
      - reminders_data:/app/reminder_db.json
    restart: unless-stopped
    environment:
      - DB_PATH=/app/reminder_db.json

volumes:
  reminders_data:
    name: catty_reminders_db
EOF

            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose -f /home/ivan/compose/docker-compose.yml pull

            docker compose -f /home/ivan/compose/docker-compose.yml down

            docker compose -f /home/ivan/compose/docker-compose.yml up -d

            docker image prune -f

            docker compose -f /home/ivan/compose/docker-compose.yml ps

            echo "Docker Compose deployment completed"
            echo "App available at http://app.alehin.course.prafdin.ru"
