name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get release commit SHA
        id: get_sha
        run: |
          COMMIT_SHA=$(git ls-remote origin "refs/tags/${{ github.event.release.tag_name }}" | cut -f1)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Deploy Docker container to VM
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 2422
          username: ivan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker stop catty-reminders || true
            docker rm catty-reminders || true

            docker run -d \
              --name catty-reminders \
              --restart unless-stopped \
              -p 8181:8181 \
              ghcr.io/ivanalehin/catty-reminders:${{ env.COMMIT_SHA }}

            echo "Deployed image: ${{ env.COMMIT_SHA }}"
            echo "App available at http://app.alehin.course.prafdin.ru"
