name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Docker Compose stack to VM
        uses: appleboy/ssh-action@v1
        with:
          host: course.prafdin.ru
          port: 2422
          username: ivan
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          upload: |
            docker-compose.yml -> /home/ivan/app/docker-compose.yml
          script: |
            cd /home/ivan/app

            echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose pull
            docker compose down
            docker compose up -d

            docker compose ps

            docker image prune -f

            echo "Docker Compose deployment completed"
            echo "App available at http://app.alehin.course.prafdin.ru"
